server:
  port: 8090
  #数据库的配置
spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: system
    password: root
    driver-class-name: oracle.jdbc.driver.OracleDriver

  #thymeleaf的配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths:
            - /**
#mapper文件的配置
mybatis:
  mapper-locations: classpath:com.elite.springbootbootstrap.mapper.*.xml
  config-location: classpath:mybatis-config.xml



